complete -c verilator -l no-aslr -d "Disable address space layout randomization"
complete -c verilator -l no-assert -d "Disable all assertions"
complete -c verilator -l no-assert-case -d "Disable unique/unique0/priority-case assertions"
complete -c verilator -l autoflush -d "Flush streams after all $displays"
complete -c verilator -l bbox-sys -d "Blackbox unknown $system calls"
complete -c verilator -l bbox-unsup -d "Blackbox unsupported language features"
complete -c verilator -l binary -d "Build model binary"
complete -c verilator -l build -d "Build model executable/library after Verilation"
complete -c verilator -l build-dep-bin -d "Override build dependency Verilator binary"
complete -c verilator -l build-jobs -d "Parallelism for --build"
complete -c verilator -l cc -d "Create C++ output"
complete -c verilator -o CFLAGS -d "C++ compiler arguments for makefile"
complete -c verilator -l compiler -d "Tune for specified C++ compiler"
complete -c verilator -l compiler-include -d "Include additional header in the precompiled one"
complete -c verilator -l converge-limit -d "Tune convergence settle time"
complete -c verilator -l coverage -d "Enable all coverage"
complete -c verilator -l coverage-expr -d "Enable expression coverage"
complete -c verilator -l coverage-expr-max -d "Maximum permutations allowed for an expression"
complete -c verilator -l coverage-line -d "Enable line coverage"
complete -c verilator -l coverage-max-width -d "Maximum array depth for coverage"
complete -c verilator -l coverage-toggle -d "Enable toggle coverage"
complete -c verilator -l coverage-underscore -d "Enable coverage of _signals"
complete -c verilator -l coverage-user -d "Enable SVL user coverage"
complete -c verilator -o D -d "Set preprocessor define"
complete -c verilator -l debug -d "Enable debugging"
complete -c verilator -l debug-check -d "Enable debugging assertions"
complete -c verilator -l no-debug-leak -d "Disable leaking memory in --debug mode"
complete -c verilator -l debugi -d "Enable debugging at a specified level"
complete -c verilator -l debugi- -d "Enable debugging a source file at a level"
complete -c verilator -l no-decoration -d "Disable comments and lower spacing level"
complete -c verilator -l decorations -d "Set output comment and spacing level"
complete -c verilator -l default-language -d "Default language to parse"
complete -c verilator -l diagnostics-sarif -d "Enable SARIF diagnostics output"
complete -c verilator -l diagnostics-sarif-output -d "Set SARIF diagnostics output file"
complete -c verilator -l dpi-hdr-only -d "Only produce the DPI header file"
complete -c verilator -l dump- -d "Enable dumping everything in source file"
complete -c verilator -l dump-defines -d "Show preprocessor defines with -E"
complete -c verilator -l dump-dfg -d "Enable dumping DfgGraphs to .dot files"
complete -c verilator -l dump-graph -d "Enable dumping V3Graphs to .dot files"
complete -c verilator -l dump-inputs -d "Enable dumping preprocessed input files"
complete -c verilator -l dump-tree -d "Enable dumping Ast .tree files"
complete -c verilator -l dump-tree-addrids -d "Use short identifiers instead of addresses"
complete -c verilator -l dump-tree-dot -d "Enable dumping Ast .tree.dot debug files"
complete -c verilator -l dump-tree-json -d "Enable dumping Ast .tree.json files and .tree.meta.json file"
complete -c verilator -l dumpi- -d "Enable dumping everything in source file at level"
complete -c verilator -l dumpi-dfg -d "Enable dumping DfgGraphs to .dot files at level"
complete -c verilator -l dumpi-graph -d "Enable dumping V3Graphs to .dot files at level"
complete -c verilator -l dumpi-tree -d "Enable dumping Ast .tree files at level"
complete -c verilator -l dumpi-tree-json -d "Enable dumping Ast .tree.json files at level"
complete -c verilator -o E -d "Preprocess, but do not compile"
complete -c verilator -l emit-accessors -d "Emit getter and setter methods for model top class"
complete -c verilator -l error-limit -d "Abort after this number of errors"
complete -c verilator -l exe -d "Link to create executable"
complete -c verilator -l expand-limit -d "Set expand optimization limit"
complete -c verilator -o F -d "Parse arguments from a file, relatively"
complete -c verilator -o f -d "Parse arguments from a file"
complete -c verilator -o FI -d "Force include of a file"
complete -c verilator -l flatten -d "Force inlining of all modules, tasks and functions"
complete -c verilator -l future0 -d "Ignore an option for compatibility"
complete -c verilator -l future1 -d "Ignore an option with argument for compatibility"
complete -c verilator -o fno- -d "Disable internal optimization stage"
complete -c verilator -o G -d "Overwrite top-level parameter"
complete -c verilator -l gate-stmts -d "Tune gate optimizer depth"
complete -c verilator -l gdb -d "Run Verilator under GDB interactively"
complete -c verilator -l gdbbt -d "Run Verilator under GDB for backtrace"
complete -c verilator -l generate-key -d "Create random key for --protect-key"
complete -c verilator -l get-supported -d "Get if feature is supported"
complete -c verilator -l getenv -d "Get environment variable with defaults"
complete -c verilator -l help -d "Show this help"
complete -c verilator -l hierarchical -d "Enable hierarchical Verilation"
complete -c verilator -l hierarchical-block -d "Internal use only for --hierarchical"
complete -c verilator -l hierarchical-child -d "Internal use only for --hierarchical"
complete -c verilator -l hierarchical-params-file -d "Internal option that specifies parameters file for hier blocks"
complete -c verilator -l hierarchical-threads -d "Number of threads for hierarchical scheduling"
complete -c verilator -o I -d "Directory to search for includes"
complete -c verilator -l if-depth -d "Tune IFDEPTH warning"
complete -c verilator -l inline-mult -d "Tune module inlining"
complete -c verilator -l instr-count-dpi -d "Assumed dynamic instruction count of DPI imports"
complete -c verilator -o j -d "Parallelism for --build-jobs/--verilate-jobs"
complete -c verilator -l no-json-edit-nums -d "Don't dump editNum in .tree.json files"
complete -c verilator -l no-json-ids -d "Don't use short identifiers instead of addresses/paths in .tree.json"
complete -c verilator -l json-only -d "Create JSON parser output (.tree.json and .meta.json)"
complete -c verilator -l json-only-meta-output -d "Set .tree.meta.json output filename"
complete -c verilator -l json-only-output -d "Set .tree.json output filename"
complete -c verilator -l l2-name -d "Verilog scope name of the top module"
complete -c verilator -l language -d "Default language standard to parse"
complete -c verilator -o LDFLAGS -d "Linker pre-object arguments for makefile"
complete -c verilator -l lib-create -d "Create a DPI library"
complete -c verilator -l lint-only -d "Lint, but do not make output"
complete -c verilator -l localize-max-size -d "Tune localize optimization variable size"
complete -c verilator -l main -d "Generate C++ main() file"
complete -c verilator -l main-top-name -d "Specify top name passed to Verilated model in generated C++ main"
complete -c verilator -l make -d "Generate scripts for specified build tool"
complete -c verilator -o MAKEFLAGS -d "Arguments to pass to make during --build"
complete -c verilator -l max-num-width -d "Maximum number width (default: 64K)"
complete -c verilator -l Mdir -d "Name of output object directory"
complete -c verilator -l MMD -d "Create .d dependency files"
complete -c verilator -l mod-prefix -d "Name to prepend to lower classes"
complete -c verilator -l MP -d "Create phony dependency targets"
complete -c verilator -o o -d "Name of final executable"
complete -c verilator -o O0 -d "Disable optimizations"
complete -c verilator -o O1 -d "Default optimizations"
complete -c verilator -o O2 -d "Stronger optimizations"
complete -c verilator -o O3 -d "High-performance optimizations"
complete -c verilator -o O -d "Selectable optimizations"
complete -c verilator -l output-groups -d "Group .cpp files into larger ones"
complete -c verilator -l output-split -d "Split .cpp files into pieces"
complete -c verilator -l output-split-cfuncs -d "Split model functions"
complete -c verilator -l output-split-ctrace -d "Split tracing functions"
complete -c verilator -o P -d "Disable line numbers and blanks with -E"
complete -c verilator -l pins-bv -d "Specify types for top-level ports"
complete -c verilator -l pins-inout-enables -d "Specify that __en and __out signals be created for inouts"
complete -c verilator -l pins-sc-biguint -d "Specify types for top-level ports"
complete -c verilator -l pins-sc-uint -d "Specify types for top-level ports"
complete -c verilator -l pins-sc-uint-bool -d "Specify types for top-level ports"
complete -c verilator -l pins-uint8 -d "Specify types for top-level ports"
complete -c verilator -l no-pins64 -d "Don't use uint64_t's for 33-64 bit sigs"
complete -c verilator -l pipe-filter -d "Filter all input through a script"
complete -c verilator -l prefix -d "Name of top-level class"
complete -c verilator -l preproc-comments -d "Include preprocessor comments in the output with -E"
complete -c verilator -l preproc-defines -d "Include preprocessor defines in the output with -E"
complete -c verilator -l preproc-resolve -d "Include all found modules in the output with -E"
complete -c verilator -l preproc-token-limit -d "Maximum tokens on a line allowed by preprocessor"
complete -c verilator -l private -d "Debugging; see docs"
complete -c verilator -l prof-c -d "Compile C++ code with profiling"
complete -c verilator -l prof-cfuncs -d "Name functions for profiling"
complete -c verilator -l prof-exec -d "Enable generating execution profile for gantt chart"
complete -c verilator -l prof-pgo -d "Enable generating profiling data for PGO"
complete -c verilator -l protect-ids -d "Hash identifier names for obscurity"
complete -c verilator -l protect-key -d "Key for symbol protection"
complete -c verilator -l protect-lib -d "Create a DPI protected library"
complete -c verilator -l public -d "Mark signals as public; see docs"
complete -c verilator -l public-depth -d "Mark public to specified module depth"
complete -c verilator -l public-flat-rw -d "Mark all variables, etc as public_flat_rw"
complete -c verilator -l public-ignore -d "Ignore all public comment markings"
complete -c verilator -l public-params -d "Mark all parameters as public_flat"
complete -c verilator -o pvalue+ -d "Overwrite toplevel parameter"
complete -c verilator -l quiet -d "Minimize additional printing"
complete -c verilator -l quiet-exit -d "Don't print the command on failure"
complete -c verilator -l quiet-stats -d "Don't print statistics"
complete -c verilator -l relative-includes -d "Resolve includes relative to current file"
complete -c verilator -l reloop-limit -d "Minimum iterations for forming loops"
complete -c verilator -l report-unoptflat -d "Extra diagnostics for UNOPTFLAT"
complete -c verilator -l rr -d "Run Verilator and record with rr"
complete -c verilator -l runtime-debug -d "Enable model runtime debugging"
complete -c verilator -l savable -d "Enable model save-restore"
complete -c verilator -l sc -d "Create SystemC output"
complete -c verilator -l no-skip-identical -d "Disable skipping identical output"
complete -c verilator -l stats -d "Create statistics file"
complete -c verilator -l stats-vars -d "Provide statistics on variables"
complete -c verilator -l no-std -d "Prevent loading standard files"
complete -c verilator -l no-std-package -d "Prevent parsing standard package"
complete -c verilator -l no-std-waiver -d "Prevent parsing standard lint waivers"
complete -c verilator -l no-stop-fail -d "Do not call $stop when assertion fails"
complete -c verilator -l structs-packed -d "Convert all unpacked structures to packed structures"
complete -c verilator -o sv -d "Enable SystemVerilog parsing"
complete -c verilator -l threads -d "Enable multithreading"
complete -c verilator -l threads-dpi -d "Enable multithreaded DPI"
complete -c verilator -l threads-max-mtasks -d "Tune maximum mtask partitioning"
complete -c verilator -l timescale -d "Sets default timescale"
complete -c verilator -l timescale-override -d "Overrides all timescales"
complete -c verilator -l timing -d "Enable timing support"
complete -c verilator -l no-timing -d "Disable timing support"
complete -c verilator -l top -d "Alias of --top-module"
complete -c verilator -l top-module -d "Name of top-level input module"
complete -c verilator -l trace -d "Enable VCD waveform creation"
complete -c verilator -l trace-coverage -d "Enable tracing of coverage"
complete -c verilator -l trace-depth -d "Depth of tracing"
complete -c verilator -l trace-fst -d "Enable FST waveform creation"
complete -c verilator -l trace-max-array -d "Maximum array depth for tracing"
complete -c verilator -l trace-max-width -d "Maximum bit width for tracing"
complete -c verilator -l trace-params -d "Enable tracing of parameters"
complete -c verilator -l trace-saif -d "Enable SAIF file creation"
complete -c verilator -l trace-structs -d "Enable tracing structure names"
complete -c verilator -l trace-threads -d "Enable FST waveform creation on separate threads"
complete -c verilator -l no-trace-top -d "Do not emit traces for signals in the top module generated by verilator"
complete -c verilator -l trace-underscore -d "Enable tracing of _signals"
complete -c verilator -l trace-vcd -d "Enable VCD waveform creation"
complete -c verilator -o U -d "Undefine preprocessor define"
complete -c verilator -l no-unlimited-stack -d "Don't disable stack size limit"
complete -c verilator -l unroll-count -d "Tune maximum loop iterations"
complete -c verilator -l unroll-stmts -d "Tune maximum loop body size"
complete -c verilator -l unused-regexp -d "Tune UNUSED lint signals"
complete -c verilator -o V -d "Verbose version and config"
complete -c verilator -o v -d "Verilog library"
complete -c verilator -l valgrind -d "Run Verilator under valgrind"
complete -c verilator -l no-verilate -d "Skip Verilation and just compile previously Verilated code"
complete -c verilator -l verilate-jobs -d "Job threads for Verilation stage"
complete -c verilator -l version -d "Show program version and exits"
complete -c verilator -l vpi -d "Enable VPI compiles"
complete -c verilator -l waiver-multiline -d "Create multiline --match for waivers"
complete -c verilator -l waiver-output -d "Create a waiver file based on linter warnings"
complete -c verilator -o Wall -d "Enable all style warnings"
complete -c verilator -o Werror- -d "Convert warnings to errors"
complete -c verilator -o Wfuture- -d "Disable unknown message warnings"
complete -c verilator -o Wno- -d "Disable warning"
complete -c verilator -o Wno-context -d "Disable source context on warnings"
complete -c verilator -o Wno-fatal -d "Disable fatal exit on warnings"
complete -c verilator -o Wno-lint -d "Disable all lint warnings"
complete -c verilator -o Wno-style -d "Disable all style warnings"
complete -c verilator -o work -d "Set config library for following files"
complete -c verilator -o Wpedantic -d "Warn on compliance-test issues"
complete -c verilator -o Wwarn- -d "Enable specified warning message"
complete -c verilator -o Wwarn-lint -d "Enable lint warning message"
complete -c verilator -o Wwarn-style -d "Enable style warning message"
complete -c verilator -l x-assign -d "Assign non-initial Xs to this value"
complete -c verilator -l x-initial -d "Assign initial Xs to this value"
complete -c verilator -l x-initial-edge -d "Enable initial X->0 and X->1 edge triggers"
complete -c verilator -l xml-only -d "Create XML parser output"
complete -c verilator -l xml-output -d "output filename"
complete -c verilator -o y -d "Directory to search for modules"
