return {
  "mason-org/mason.nvim",

  opts = {
    ensure_installed = {
      "arduino-language-server",
      "bash-debug-adapter",
      "bash-language-server",
      "bibtex-tidy",
      "clang-format",
      "clangd",
      "codelldb",
      "cssmodules-language-server",
      "debugpy",
      "fish-lsp",
      "json-lsp",
      -- "kdlfmt",
      "latexindent",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "nil",
      "nixfmt",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "stylua",
      "svlangserver",
      "taplo",
      "texlab",
      "tree-sitter-cli",
      "verible",
    },
  },
}
